### ISSUE TITLE
Crash when opening TestActivity

### ISSUE THREAD

**Issue by Swarthon** [Sw24Softwares/StarkeVerben#12]
A crash is happening when TestActivity is opened

Log : 
11-21 21:43:42.588 19838 19838 E AndroidRuntime: FATAL EXCEPTION: main
11-21 21:43:42.588 19838 19838 E AndroidRuntime: Process: org.sw24softwares.starkeverben, PID: 19838
11-21 21:43:42.588 19838 19838 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.sw24softwares.starkeverben/org.sw24softwares.starkeverben.TestActivity}: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 4
11-21 21:43:42.588 19838 19838 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
11-21 21:43:42.588 19838 19838 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
11-21 21:43:42.588 19838 19838 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
11-21 21:43:42.588 19838 19838 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
11-21 21:43:42.588 19838 19838 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-21 21:43:42.588 19838 19838 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-21 21:43:42.588 19838 19838 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6236)
11-21 21:43:42.588 19838 19838 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-21 21:43:42.588 19838 19838 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
11-21 21:43:42.588 19838 19838 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
11-21 21:43:42.588 19838 19838 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 4
11-21 21:43:42.588 19838 19838 E AndroidRuntime: 	at java.util.Vector.get(Vector.java:748)
11-21 21:43:42.588 19838 19838 E AndroidRuntime: 	at org.sw24softwares.starkeverben.TestActivity.onCreate(TestActivity.java:63)
11-21 21:43:42.588 19838 19838 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6684)
11-21 21:43:42.588 19838 19838 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
11-21 21:43:42.588 19838 19838 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
11-21 21:43:42.588 19838 19838 E AndroidRuntime: 	... 9 more

This happens with the rebuild of the back : 5687131f44c07c8583a6f0c97f7a1d5d048fd38d

**Comment by Swarthon** [comment]
Solved by splitting translations possibilities and forms possibilities.
